### ISSUE TITLE
Setting standard icon failed

### ISSUE THREAD

**Issue by wfx** [DaveMDS/eluminance#1]
Hi,
used versions:
EFL 1.15.1
Elementary  1.15.1
Python-EFL  1.15.0  (won the fight against cython :) )

Eluminace produce this error if you click on the info button.

[wfx@N750JV ~]$ eluminance
Traceback (most recent call last):
  File "efl.evas_object_smart.pxi", line 426, in efl.evas._smart_callback (efl/evas/efl.evas.c:78475)
  File "/usr/lib/python3.4/site-packages/eluminance/eluminance.py", line 733, in _buttons_cb
    InfoWin(self.parent)
  File "/usr/lib/python3.4/site-packages/eluminance/eluminance.py", line 815, in __init__
    ic = Icon(self, standard='eluminance', size_hint_min=(64,64))
  File "efl/elementary/icon.pxi", line 38, in efl.elementary.**init**.Icon.**init** (efl/elementary/**init**.c:154685)
  File "efl.evas_object.pxi", line 209, in efl.evas.Object._set_properties_from_keyword_args (efl/evas/efl.evas.c:51589)
  File "efl.eo.pyx", line 272, in efl.eo.Eo._set_properties_from_keyword_args (efl/eo/efl.eo.c:3228)
  File "efl/elementary/icon.pxi", line 109, in efl.elementary.__init__.Icon.standard.**set** (efl/elementary/**init**.c:155282)
RuntimeWarning: Setting standard icon failed

**Comment by DaveMDS** [comment]
hmm, strange, I'm not getting this error here
It cannot find the "eluminance" icon... can you see the icon in the e main menu? and in the window border?

do you have the icon installed? it should be in:
/usr/local/share/icons/hicolor/48x48/apps/eluminance.png
or whatever prefix you install to, look at the installed_files.txt, it show all the installed files

**Comment by wfx** [comment]
My e is under /usr/local.
Eluminace not.
The icons are under /usr/share... manualy copy to /usr/local/... works.
