### ISSUE TITLE
Setting standard icon failed (zoom-fill)

### ISSUE THREAD

**Issue by Commod0re** [DaveMDS/eluminance#2]
I am currently getting this traceback upon starting eluminance due to a missing icon reference: 

``` python-traceback
Traceback (most recent call last):
  File "/usr/bin/eluminance", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/eluminance/eluminance.py", line 899, in
 main
    app = EluminanceApp()
  File "/usr/lib/python3.5/site-packages/eluminance/eluminance.py", line 838, in __init__
    self.sshow = SlideShow(self.win, self.photo_changed, self.zoom_changed)
  File "/usr/lib/python3.5/site-packages/eluminance/eluminance.py", line 666, in __init__
    w = StdButton(self, icon=icon)
  File "/usr/lib/python3.5/site-packages/eluminance/eluminance.py", line 87, in __init__
    self.icon = icon
  File "/usr/lib/python3.5/site-packages/eluminance/eluminance.py", line 99, in icon
    self.content = elm.Icon(self, standard=name, size_hint_min=(18,18))
  File "efl/elementary/icon.pxi", line 38, in efl.elementary.__init__.Icon.__init__ (efl/elementary/__init__.c:154226)
  File "efl/evas/efl.evas_object.pxi", line 209, in efl.evas.Object._set_properties_from_keyword_args (efl/evas/efl.evas.c:51771)
  File "efl/eo/efl.eo.pyx", line 273, in efl.eo.Eo._set_properties_from_keyword_args (efl/eo/efl.eo.c:3311)
  File "efl/elementary/icon.pxi", line 109, in efl.elementary.__init__.Icon.standard.__set__ (efl/elementary/__init__.c:154823)
RuntimeWarning: Setting standard icon failed
```

Basic debugging indicates that it is the 'zoom-fill' icon that causes this error. Changing the string on line 628 to something else (I used 'zoom-fit-best' to test) makes it work.

Dependency versions in use:
- efl 1.17.0
- elementary 1.17.0
- python-efl 1.17.0
- python-xdg 0.25
- python 3.5.2

I built/installed on Arch Linux with a pkgbuild that I maintain on the [AUR](https://aur.archlinux.org/packages/eluminance-git/), so it is entirely possible that this error is my doing

**Comment by DaveMDS** [comment]
Yep, you right, that icon is in EFL only from the 1.18 release (that will come out the next week)

I will probably rise the eluminance dependency to EFL 1.18 next week, but I'm still not sure, need to think a bit more on this issue

**Comment by DaveMDS** [comment]
This is now fixed, eluminance will not crash if an icon is not find
Note that now you need efl >= 1.18.0 (not only for icons, other stuff has been fixed)

Thanks for the report
